name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@damacchi'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build lib
        run: pnpm --filter @damacchi/ui build

      - name: Publish to GitHub Packages
        run: pnpm --filter @damacchi/ui publish --access restricted --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
